### ISSUE TITLE
There is no session with session with id [xxxxx]

### ISSUE THREAD

**Issue by flygan1988** [wuyouzhuguli/FEBS-Shiro#143]
### 问题描述
用户登出后再登陆，执行修改等操作后台报错没有session id

### 相关错误
`org.apache.shiro.session.UnknownSessionException: There is no session with id [0d5a3076-3c93-40d1-b506-55ef055d92db]
	at org.apache.shiro.session.mgt.eis.AbstractSessionDAO.readSession(AbstractSessionDAO.java:170)
	at org.apache.shiro.session.mgt.DefaultSessionManager.retrieveSessionFromDataSource(DefaultSessionManager.java:236)
	at org.apache.shiro.session.mgt.DefaultSessionManager.retrieveSession(DefaultSessionManager.java:222)
	at org.apache.shiro.session.mgt.AbstractValidatingSessionManager.doGetSession(AbstractValidatingSessionManager.java:118)
	at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupSession(AbstractNativeSessionManager.java:148)
	at org.apache.shiro.session.mgt.AbstractNativeSessionManager.lookupRequiredSession(AbstractNativeSessionManager.java:152)
	at org.apache.shiro.session.mgt.AbstractNativeSessionManager.getAttribute(AbstractNativeSessionManager.java:249)
	at org.apache.shiro.session.mgt.DelegatingSession.getAttribute(DelegatingSession.java:141)
	at org.apache.shiro.session.ProxiedSession.getAttribute(ProxiedSession.java:121)
	at org.apache.shiro.subject.support.DelegatingSubject.getRunAsPrincipalsStack(DelegatingSubject.java:473)
	at org.apache.shiro.subject.support.DelegatingSubject.getPrincipals(DelegatingSubject.java:157)
	at org.apache.shiro.subject.support.DelegatingSubject.getPrincipal(DelegatingSubject.java:153)
	at cc.mrbird.febs.monitor.service.impl.LogServiceImpl.saveLog(LogServiceImpl.java:82)
	at cc.mrbird.febs.monitor.service.impl.LogServiceImpl$$FastClassBySpringCGLIB$$2e363d6.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

> issue模板，by MrBird.

**Comment by robinliu2827** [comment]
这个是异步线程造成的。

**Comment by robinliu2827** [comment]
操作日志记录切面类（ControllerEndpointAspect）中，logService.saveLog这个方法为异步的操作，SecurityUtils.getSubject().getPrincipal()在异步线程中会丢失Session信息。
所以修改为：
User user = (User) SecurityUtils.getSubject().getPrincipal()
logService.saveLog(user, point, targetMethod, ip, operation, start);

**Comment by wuyouzhuguli** [comment]
@robinliu2827 收到，您可以提交个pr，或者我有空修复。

**Comment by robinliu2827** [comment]
收到，已提交pr。



robinliu2827@163.com
 
From: mrbird
Date: 2020-05-22 10:10
To: wuyouzhuguli/FEBS-Shiro
CC: robinLiu; Mention
Subject: Re: [wuyouzhuguli/FEBS-Shiro] There is no session with session with id [xxxxx] (#143)
@robinliu2827 收到，您可以提交个pr，或者我有空修复。
