### ISSUE TITLE
运行项目报错Caused by: java.lang.ClassCastException: cc.mrbird.febs.job.entity.Job cannot be cast to cc.mrbird.febs.job.entity.Job

### ISSUE THREAD

**Issue by cwh643** [wuyouzhuguli/FEBS-Shiro#80]
### 问题描述
运行项目报错
Caused by: java.lang.ClassCastException: cc.mrbird.febs.job.entity.Job cannot be cast to cc.mrbird.febs.job.entity.Job

### 复现步骤
运行环境 java8 idea

### 相关截图
2019-07-02 14:00:27 | ERROR | FEBS_Scheduler_Worker-2 | org.quartz.core.ErrorLogger | Job (DEFAULT.TASK_3 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.ClassCastException: cc.mrbird.febs.job.entity.Job cannot be cast to cc.mrbird.febs.job.entity.Job
	at cc.mrbird.febs.job.util.ScheduleJob.executeInternal(ScheduleJob.java:29)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 common frames omitted

> issue模板，by MrBird.

**Comment by wuyouzhuguli** [comment]
去掉devtools 依赖即可

**Comment by cwh643** [comment]
多谢，可以了
